language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-naokis' ]; then cd .. && eval "mv $currentfolder generator-naokis" && cd generator-naokis; fi

